<?php $_order = $block->getLayout()->getBlock('items')->getOrder(); ?>
<?php if ($_order): ?>
    <table cellspacing="0" cellpadding="0" border="0" width="650" style="border:1px solid #EAEAEA;">
        <thead>
        <tr>
            <th align="left" bgcolor="#EAEAEA"
                style="font-size:13px; padding:3px 9px"><?php echo __('Item') ?></th>
            <th align="left" bgcolor="#EAEAEA"
                style="font-size:13px; padding:3px 9px"><?php echo __('Sku') ?></th>
            <th align="center" bgcolor="#EAEAEA"
                style="font-size:13px; padding:3px 9px"><?php echo __('Qty') ?></th>
            <th align="right" bgcolor="#EAEAEA"
                style="font-size:13px; padding:3px 9px"><?php echo __('Subtotal') ?></th>
        </tr>
        </thead>

        <?php $i = 0;
        foreach ($_order->getAllItems() as $_item): ?>
            <?php if ($_item->getParentItem()) continue; else $i++; ?>
            <tbody<?php echo $i % 2 ? ' bgcolor="#F6F6F6"' : '' ?>>
            <?php echo $this->getItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>

        <tbody>
        <?php echo $this->getChildHtml('order_totals') ?>
        </tbody>
    </table>
    <?php if (\Magento\Framework\App\ObjectManager::getInstance()->get('Magento\GiftMessage\Helper\Message')->isMessagesAvailable('order', $_order, $_order->getStore()) && $_order->getGiftMessageId()): ?>
        <?php $_giftMessage = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\GiftMessage\Helper\Message')->getGiftMessage($_order->getGiftMessageId()); ?>
        <?php if ($_giftMessage): ?>
            <br/>
            <table cellspacing="0" cellpadding="0" border="0" width="100%" style="border:1px solid #EAEAEA;">
                <thead>
                <tr>
                    <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px">
                        <strong><?php echo __('Gift Message for this Order') ?></strong></th>
                </tr>
                </thead>
            </table>
        <?php endif; ?>
    <?php endif; ?>
    <?php $_history = $_order->getVisibleStatusHistory() ?>
    <?php if (count($_history)): ?>
        <div class="order-additional order-comments">
            <h4 class="sub-title"><?php echo __('Order Comment(s)') ?></h4>
            <dl class="order-about">
                <?php foreach ($_history as $_historyItem): ?>
                    <dt><?php echo $this->formatDate($_historyItem->getCreatedAtStoreDate(), 'medium', true) ?></dt>
                    <dd><?php echo $this->escapeHtml($_historyItem->getComment()) ?></dd>
                <?php endforeach; ?>
            </dl>
        </div>
    <?php endif; ?>
<?php endif; ?>
